fail_fast: true

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  ### Python specific hooks

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.2
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.2
    hooks:
      - id: uv-sync
        args: [ "--locked", "--all-packages" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [ --fix ]

  ### Local hooks

  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run ty check .
        language: system
        types: [ python ]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
